feat: Implement docker-compose with testing
skprpi/Messenger pull request #1
Opened 2022-09-10 19:54 UTC by skprpi

2022-09-13 07:47 UTC, VladimirBalun requested changes

2022-09-13 07:47 UTC, VladimirBalun commented on microservices/Dockerfile.m2m_chat_service
> +FROM ubuntu:focal
Лучше именовать просто Dockerfile

2022-09-13 07:47 UTC, VladimirBalun commented on docker-compose.yml
> +  mongodb:
Только volume нет, после рестарта все в БД будет пропадать

2022-09-13 07:47 UTC, VladimirBalun commented on docker-compose.yml
> +    command: bash -c "cd m2m_chat_service && chmod +x ./build.sh && ./build.sh"
А почему ты здесь билдишь? Лучше сюда отдавать готовый image

2022-09-13 07:47 UTC, VladimirBalun commented on .github/workflows/pipeline.yml
> +      - name: Build docker compose
Кажется, лучше сначала все побилдить, а только затем делать работу по докеру

2022-09-13 07:48 UTC, VladimirBalun commented
Лучше еще сделать глобальный CMakeLists.txt и через add_subdirectory добавлять дочерние

2022-09-13 07:49 UTC, VladimirBalun commented
И зачем ты папки build сохраняешь? По хорошему они должны скриптом создаваться

2022-09-13 17:45 UTC, skprpi commented on docker-compose.yml
> +    command: bash -c "cd m2m_chat_service && chmod +x ./build.sh && ./build.sh"
Fixed

2022-09-13 17:48 UTC, skprpi commented on microservices/Dockerfile.m2m_chat_service
> +FROM ubuntu:focal
Renamed to Dockerfile

2022-09-13 17:57 UTC, skprpi commented on docker-compose.yml
> +  mongodb:
Added volumes

2022-09-14 15:55 UTC, skprpi commented on .github/workflows/pipeline.yml
> +      - name: Build docker compose
Fixed

2022-09-15 09:09 UTC, VladimirBalun approved these changes

2022-09-18 08:33 UTC, merged